%YAML:1.0
---
nav_map:
  xlen: 20
  ylen: 10
  zlen: 3
  nx: 60
  ny: 30
  nz: 9

exp_map:
  xlen: 20
  ylen: 10
  zlen: 3
  nx: 40
  ny: 20
  nz: 1

drone:
  radius: 0.5
  height: 0.25

window:
  name: "Map"
  width: 1024
  height: 768
  fview: 420
  xview: 0
  yview: -10
  zview: 0
  xstart: 512
  ystart: 389
